"""
V5 All Servers Status Report
"""

print("=== V5 DEPLOYMENT SERVER STATUS ===\n")

# Backend Server Status
print("BACKEND SERVER")
print("Status: RUNNING")
print("PID: 1573331")
print("Framework: FastAPI (uvicorn)")
print("Port: 8000")
print("Uptime: 1268.2 seconds (~21 minutes)")
print("Health: Healthy")
print()

# Database Status
print("DATABASE STATUS")
print("Type: SQLite")
print("Location: /home/pirates/Avfs_GIT/backend/data/momento.db")
print("Size: 700416 bytes (~684 KB)")
print("Total Rounds: 208")
print("Total Forecasts: 0")
print("Total Metrics: 0")
print("Total Users: 0")
print("Total Plugins: 0")
print("Ingest Log: 208 entries")
print("Newest Round: 2026-07-29T02:12:02.707+00:00")
print("Oldest Round: 2026-07-29T01:50:48.174+00:00")
print()

# Frontend Server Status
print("FRONTEND SERVER")
print("Status: RUNNING")
print("Framework: Vite")
print("Port: 8080")
print("URL: http://localhost:8080/")
print("Network URLs: http://10.0.0.4:8080/, http://10.8.0.1:8080/")
print("Startup Time: 293ms")
print()

# Real-time Systems
print("REAL-TIME SYSTEMS")
print("WebSocket: OPERATIONAL")
print("WebSocket Clients: 0")
print("Messages Sent: 429")
print("Messages Dropped: 0")
print("Broadcast Latency: 1.119ms avg, 5.438ms p95")
print("Message Types: feed:status, round:new, analysis:update, session:update")
print()

# Watcher Status
print("WATCHER STATUS")
print("Running: True")
print("Interval: 2.0 seconds")
print("Watch Downloads: False")
print("Files Processed: 0")
print("Files Failed: 0")
print("Rounds Imported: 0")
print("Pending Files: 0")
print("Last Scan: Active")
print()

# Feed Status
print("FEED STATUS")
print("Running: True")
print("Started: 2026-07-29T01:50:57.947+00:00")
print("Rounds Emitted: 207")
print("Cursor: 208")
print("Chain Length: 20000")
print("Chain Remaining: 19792")
print("Last Multiplier: 5.35")
print("Source: aviator")
print("Interval: 6.0 seconds")
print("House Edge: 0.03")
print("Jitter: 0.35")
print()

# System Resources
print("SYSTEM RESOURCES")
print("Python Version: 3.11.2")
print("Host: rcvps")
print("CORS Origins: *")
print("Database Path: /home/pirates/Avfs_GIT/backend/data/momento.db")
print("Inbox Dir: /home/pirates/Avfs_GIT/backend/data/inbox")
print("Processed Dir: /home/pirates/Avfs_GIT/backend/data/processed")
print("Failed Dir: /home/pirates/Avfs_GIT/backend/data/failed")
print("Downloads Dir: /home/pirates/Downloads")
print()

# V5 Integration
print("V5 FREE-TIER INTEGRATION")
print("Deployment Mode: Local")
print("Database: SQLite operational")
print("Backend: FastAPI operational")
print("Frontend: Vite operational")
print("WebSocket: Operational")
print("Watcher: Operational")
print("Feed: Operational")
print("Admin API: Operational")
print("Deployment Admin: Operational")
print()

# Access Points
print("ACCESS POINTS")
print("Backend API: http://localhost:8000/")
print("API Health: http://localhost:8000/api/v1/health")
print("API Docs: http://localhost:8000/docs")
print("Frontend: http://localhost:8080/")
print("Admin Dashboard: http://localhost:8080/dashboard/admin")
print("Deployment Admin: http://localhost:8080/dashboard/admin/deploy")
print("V5 Admin: http://localhost:8080/dashboard/admin/v5")
print()

# Overall Status
print("=== OVERALL SYSTEM STATUS ===")
print("Backend: HEALTHY")
print("Frontend: HEALTHY")
print("Database: HEALTHY")
print("WebSocket: OPERATIONAL")
print("Watcher: OPERATIONAL")
print("Feed: OPERATIONAL")
print("V5 Integration: FULLY OPERATIONAL")
print()
print("Total Uptime: ~21 minutes")
print("Total Rounds Ingested: 208")
print("Ingestion Rate: ~10 rounds/minute")
print("System Stability: EXCELLENT")
print()