---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: momento-compute-resources
  namespace: momento-v5
  labels:
    app: momento
    version: v5
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 40Gi
    persistentvolumeclaims: "10"
    requests.storage: "100Gi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: momento-limits
  namespace: momento-v5
  labels:
    app: momento
    version: v5
spec:
  limits:
  - default:
      cpu: "1000m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    max:
      cpu: "4000m"
      memory: "4Gi"
    min:
      cpu: "50m"
      memory: "64Mi"
    type: Container
  - max:
      cpu: "8000m"
      memory: "8Gi"
    min:
      cpu: "100m"
      memory: "128Mi"
    type: Pod
